---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "target-branch"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    target-branch: "target-branch"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
    target-branch: "target-branch"
